name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: extractions/setup-just@v3

      - name: Build Docker CI image
        run: just build-ci-docker $(id -u)

      - name: Build (for source generators)
        run: just build

      - name: Check Format
        run: just check-format

  test-static_analysis:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          # Disabling shallow clones is recommended for improving the relevancy of reporting
          fetch-depth: 0

      - uses: extractions/setup-just@v3

      - name: Build Docker CI image
        run: just build-ci-docker $(id -u)

      - name: Build (for source generators)
        run: just build

      - name: Test
        run: just test tmp

      - name: SonarQubeScan
        uses: SonarSource/sonarqube-scan-action@bfd4e558cda28cda6b5defafb9232d191be8c203
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

